#!/usr/bin/env python3
"""Rewrite git commit IDs into jj change IDs in tool output before the model sees it.

Registered as a PostToolUse hook by the /daniel skill and the impl and jj agents.
Commit IDs are regenerated by every rewrite, so a model that holds one holds a
stale reference; change IDs survive squash, describe and rebase. Candidates are
7-40 hex chars with at least one digit and one letter, which excludes change IDs
(k-z alphabet), UUID segments, sha256 digests and hex colors. Only tokens that
actually resolve to a commit in this repository are replaced; anything else is
left alone.
"""
import json
import re
import subprocess
import sys

CANDIDATE = re.compile(r"(?<![0-9A-Za-z-])[0-9a-f]{7,40}(?![0-9A-Za-z-])")
TEMPLATE = 'commit_id ++ " " ++ change_id.shortest() ++ "\\n"'


def is_candidate(token):
    return any(c.isdigit() for c in token) and any(c.isalpha() for c in token)


def walk(node, fn):
    if isinstance(node, str):
        return fn(node)
    if isinstance(node, dict):
        return {k: walk(v, fn) for k, v in node.items()}
    if isinstance(node, list):
        return [walk(v, fn) for v in node]
    return node


def collect(node):
    found = set()

    def note(text):
        found.update(t for t in CANDIDATE.findall(text) if is_candidate(t))
        return text

    walk(node, note)
    return found


def resolve(tokens, cwd):
    """Map each token that names a commit to that commit's change ID.

    --ignore-working-copy keeps this read-only: the /daniel agents share one
    repository across workspaces, and a snapshot from a hook firing on every
    Bash call would rewrite the working-copy commit another agent is editing.
    """
    revset = " | ".join(f"present({t})" for t in sorted(tokens))
    try:
        result = subprocess.run(
            ["jj", "log", "--ignore-working-copy", "--color=never", "--no-graph",
             "-r", revset, "-T", TEMPLATE],
            cwd=cwd or None, capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return {}
    if result.returncode != 0:
        # ponytail: an ambiguous prefix fails the whole batch; resolve per token
        # if that ever shows up in practice.
        return {}
    pairs = [line.split() for line in result.stdout.splitlines() if line.strip()]
    return {token: change for token in tokens
            for commit, change in pairs if commit.startswith(token)}


def main():
    try:
        event = json.load(sys.stdin)
    except ValueError:
        return 0

    output = event.get("tool_response")
    if output is None:
        return 0

    tokens = collect(output)
    if not tokens:
        return 0

    mapping = resolve(tokens, event.get("cwd", ""))
    if not mapping:
        return 0

    def rewrite(text):
        return CANDIDATE.sub(lambda m: mapping.get(m.group(), m.group()), text)

    json.dump({"hookSpecificOutput": {
        "hookEventName": "PostToolUse",
        "updatedToolOutput": walk(output, rewrite),
        "additionalContext": (
            f"{len(mapping)} git commit ID(s) in this output were replaced by the "
            "jj change ID of the same commit. Refer to commits by those change IDs."
        ),
    }}, sys.stdout)
    return 0


def test():
    assert collect({"stdout": "landed as a1b2c3d4"}) == {"a1b2c3d4"}
    assert collect({"stdout": "squash --into kmzlrpqx"}) == set()
    assert collect({"stdout": "session 3672a918-75c1-47b6"}) == set()
    assert collect({"stdout": "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}) == set()
    assert collect({"stdout": "defaced facade 12345678 #a1b2c3 0xdeadbeef"}) == set()
    assert collect({"a": ["x a1b2c3d4", {"b": "y b2c3d4e5"}]}) == {"a1b2c3d4", "b2c3d4e5"}
    assert walk({"a": ["b", 1, None]}, str.upper) == {"a": ["B", 1, None]}
    print("ok")


if __name__ == "__main__":
    sys.exit(test() if "--test" in sys.argv else main())
